language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - phpunit --configuration phpunit.xml --coverage-text;

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
